"use client";
import { withLicense } from "./withLicense.js";

import { SignalMeter as _SignalMeter } from "./_raw.js";
import { PulseTag as _PulseTag } from "./_raw.js";
import { StatusLight as _StatusLight } from "./_raw.js";
import { HeartbeatLine as _HeartbeatLine } from "./_raw.js";
import { LoadBar as _LoadBar } from "./_raw.js";
import { BootSequence as _BootSequence } from "./_raw.js";
import { BatteryMeter as _BatteryMeter } from "./_raw.js";
import { Uptime as _Uptime } from "./_raw.js";
import { PingIndicator as _PingIndicator } from "./_raw.js";
import { ConnectionStatus as _ConnectionStatus } from "./_raw.js";
import { AlertBanner as _AlertBanner } from "./_raw.js";
import { ReadyBadge as _ReadyBadge } from "./_raw.js";
import { ScanLine as _ScanLine } from "./_raw.js";
import { NetworkPulse as _NetworkPulse } from "./_raw.js";
import { CPUSparkline as _CPUSparkline } from "./_raw.js";
import { ErrorRate as _ErrorRate } from "./_raw.js";
import { MemoryBar as _MemoryBar } from "./_raw.js";
import { DotChart as _DotChart } from "./_raw.js";
import { BarSparkline as _BarSparkline } from "./_raw.js";
import { FrequencyBars as _FrequencyBars } from "./_raw.js";
import { BinaryStream as _BinaryStream } from "./_raw.js";
import { VUMeter as _VUMeter } from "./_raw.js";
import { HexDump as _HexDump } from "./_raw.js";
import { GlitchCycler as _GlitchCycler } from "./_raw.js";
import { Typewriter as _Typewriter } from "./_raw.js";
import { GlitchText as _GlitchText } from "./_raw.js";
import { LogStream as _LogStream } from "./_raw.js";
import { CounterUp as _CounterUp } from "./_raw.js";
import { BootLog as _BootLog } from "./_raw.js";
import { MatrixRain as _MatrixRain } from "./_raw.js";
import { CornerOrnament as _CornerOrnament } from "./_raw.js";
import { Barcode as _Barcode } from "./_raw.js";
import { PanelTitle as _PanelTitle } from "./_raw.js";
import { PixelDiamond as _PixelDiamond } from "./_raw.js";
import { ChevronRow as _ChevronRow } from "./_raw.js";
import { DataLabel as _DataLabel } from "./_raw.js";
import { PixelClock as _PixelClock } from "./_raw.js";
import { UnixTimestamp as _UnixTimestamp } from "./_raw.js";
import { DayProgress as _DayProgress } from "./_raw.js";
import { DialGauge as _DialGauge } from "./_raw.js";
import { TankLevel as _TankLevel } from "./_raw.js";
import { FlowMeter as _FlowMeter } from "./_raw.js";
import { OrbitSystem as _OrbitSystem } from "./_raw.js";
import { TargetReticle as _TargetReticle } from "./_raw.js";
import { PriorityBadge as _PriorityBadge } from "./_raw.js";
import { RegistrationMark as _RegistrationMark } from "./_raw.js";
import { ArchiveTag as _ArchiveTag } from "./_raw.js";
import { CopyButton as _CopyButton } from "./_raw.js";
import { RatingDots as _RatingDots } from "./_raw.js";
import { SpinDial as _SpinDial } from "./_raw.js";
import { ScanBeam as _ScanBeam } from "./_raw.js";
import { SystemLoad as _SystemLoad } from "./_raw.js";
import { EventTicker as _EventTicker } from "./_raw.js";
import { SignalQuality as _SignalQuality } from "./_raw.js";
import { WatchdogTimer as _WatchdogTimer } from "./_raw.js";
import { WaveformLine as _WaveformLine } from "./_raw.js";
import { RadarSweep as _RadarSweep } from "./_raw.js";
import { PacketFlow as _PacketFlow } from "./_raw.js";
import { HeatGrid as _HeatGrid } from "./_raw.js";
import { ThermalBar as _ThermalBar } from "./_raw.js";
import { KanaTag as _KanaTag } from "./_raw.js";
import { MicroStrip as _MicroStrip } from "./_raw.js";
import { WeatherStrip as _WeatherStrip } from "./_raw.js";
import { ScrollingText as _ScrollingText } from "./_raw.js";
import { BinaryCounter as _BinaryCounter } from "./_raw.js";
import { SectorBadge as _SectorBadge } from "./_raw.js";
import { RulerTick as _RulerTick } from "./_raw.js";
import { CoordLabel as _CoordLabel } from "./_raw.js";
import { WireFrame as _WireFrame } from "./_raw.js";
import { HexGrid as _HexGrid } from "./_raw.js";
import { CountdownTimer as _CountdownTimer } from "./_raw.js";
import { StopwatchDisplay as _StopwatchDisplay } from "./_raw.js";
import { TimezoneBar as _TimezoneBar } from "./_raw.js";
import { PressureGauge as _PressureGauge } from "./_raw.js";
import { VoltageDisplay as _VoltageDisplay } from "./_raw.js";
import { TemperatureBar as _TemperatureBar } from "./_raw.js";
import { CompassRose as _CompassRose } from "./_raw.js";
import { Speedometer as _Speedometer } from "./_raw.js";
import { ToggleSwitch as _ToggleSwitch } from "./_raw.js";
import { NumericStepper as _NumericStepper } from "./_raw.js";
import { SegmentedBar as _SegmentedBar } from "./_raw.js";
import { RadarReticle as _RadarReticle } from "./_raw.js";
import { CrosshairTarget as _CrosshairTarget } from "./_raw.js";
import { MissionStatus as _MissionStatus } from "./_raw.js";

// Licensed components (stop rendering after trial expires)
export const SignalMeter = withLicense(_SignalMeter, "SignalMeter");
export const PulseTag = withLicense(_PulseTag, "PulseTag");
export const StatusLight = withLicense(_StatusLight, "StatusLight");
export const HeartbeatLine = withLicense(_HeartbeatLine, "HeartbeatLine");
export const LoadBar = withLicense(_LoadBar, "LoadBar");
export const BootSequence = withLicense(_BootSequence, "BootSequence");
export const BatteryMeter = withLicense(_BatteryMeter, "BatteryMeter");
export const Uptime = withLicense(_Uptime, "Uptime");
export const PingIndicator = withLicense(_PingIndicator, "PingIndicator");
export const ConnectionStatus = withLicense(_ConnectionStatus, "ConnectionStatus");
export const AlertBanner = withLicense(_AlertBanner, "AlertBanner");
export const ReadyBadge = withLicense(_ReadyBadge, "ReadyBadge");
export const ScanLine = withLicense(_ScanLine, "ScanLine");
export const NetworkPulse = withLicense(_NetworkPulse, "NetworkPulse");
export const CPUSparkline = withLicense(_CPUSparkline, "CPUSparkline");
export const ErrorRate = withLicense(_ErrorRate, "ErrorRate");
export const MemoryBar = withLicense(_MemoryBar, "MemoryBar");
export const DotChart = withLicense(_DotChart, "DotChart");
export const BarSparkline = withLicense(_BarSparkline, "BarSparkline");
export const FrequencyBars = withLicense(_FrequencyBars, "FrequencyBars");
export const BinaryStream = withLicense(_BinaryStream, "BinaryStream");
export const VUMeter = withLicense(_VUMeter, "VUMeter");
export const HexDump = withLicense(_HexDump, "HexDump");
export const GlitchCycler = withLicense(_GlitchCycler, "GlitchCycler");
export const Typewriter = withLicense(_Typewriter, "Typewriter");
export const GlitchText = withLicense(_GlitchText, "GlitchText");
export const LogStream = withLicense(_LogStream, "LogStream");
export const CounterUp = withLicense(_CounterUp, "CounterUp");
export const BootLog = withLicense(_BootLog, "BootLog");
export const MatrixRain = withLicense(_MatrixRain, "MatrixRain");
export const CornerOrnament = withLicense(_CornerOrnament, "CornerOrnament");
export const Barcode = withLicense(_Barcode, "Barcode");
export const PanelTitle = withLicense(_PanelTitle, "PanelTitle");
export const PixelDiamond = withLicense(_PixelDiamond, "PixelDiamond");
export const ChevronRow = withLicense(_ChevronRow, "ChevronRow");
export const DataLabel = withLicense(_DataLabel, "DataLabel");
export const PixelClock = withLicense(_PixelClock, "PixelClock");
export const UnixTimestamp = withLicense(_UnixTimestamp, "UnixTimestamp");
export const DayProgress = withLicense(_DayProgress, "DayProgress");
export const DialGauge = withLicense(_DialGauge, "DialGauge");
export const TankLevel = withLicense(_TankLevel, "TankLevel");
export const FlowMeter = withLicense(_FlowMeter, "FlowMeter");
export const OrbitSystem = withLicense(_OrbitSystem, "OrbitSystem");
export const TargetReticle = withLicense(_TargetReticle, "TargetReticle");
export const PriorityBadge = withLicense(_PriorityBadge, "PriorityBadge");
export const RegistrationMark = withLicense(_RegistrationMark, "RegistrationMark");
export const ArchiveTag = withLicense(_ArchiveTag, "ArchiveTag");
export const CopyButton = withLicense(_CopyButton, "CopyButton");
export const RatingDots = withLicense(_RatingDots, "RatingDots");
export const SpinDial = withLicense(_SpinDial, "SpinDial");
export const ScanBeam = withLicense(_ScanBeam, "ScanBeam");
export const SystemLoad = withLicense(_SystemLoad, "SystemLoad");
export const EventTicker = withLicense(_EventTicker, "EventTicker");
export const SignalQuality = withLicense(_SignalQuality, "SignalQuality");
export const WatchdogTimer = withLicense(_WatchdogTimer, "WatchdogTimer");
export const WaveformLine = withLicense(_WaveformLine, "WaveformLine");
export const RadarSweep = withLicense(_RadarSweep, "RadarSweep");
export const PacketFlow = withLicense(_PacketFlow, "PacketFlow");
export const HeatGrid = withLicense(_HeatGrid, "HeatGrid");
export const ThermalBar = withLicense(_ThermalBar, "ThermalBar");
export const KanaTag = withLicense(_KanaTag, "KanaTag");
export const MicroStrip = withLicense(_MicroStrip, "MicroStrip");
export const WeatherStrip = withLicense(_WeatherStrip, "WeatherStrip");
export const ScrollingText = withLicense(_ScrollingText, "ScrollingText");
export const BinaryCounter = withLicense(_BinaryCounter, "BinaryCounter");
export const SectorBadge = withLicense(_SectorBadge, "SectorBadge");
export const RulerTick = withLicense(_RulerTick, "RulerTick");
export const CoordLabel = withLicense(_CoordLabel, "CoordLabel");
export const WireFrame = withLicense(_WireFrame, "WireFrame");
export const HexGrid = withLicense(_HexGrid, "HexGrid");
export const CountdownTimer = withLicense(_CountdownTimer, "CountdownTimer");
export const StopwatchDisplay = withLicense(_StopwatchDisplay, "StopwatchDisplay");
export const TimezoneBar = withLicense(_TimezoneBar, "TimezoneBar");
export const PressureGauge = withLicense(_PressureGauge, "PressureGauge");
export const VoltageDisplay = withLicense(_VoltageDisplay, "VoltageDisplay");
export const TemperatureBar = withLicense(_TemperatureBar, "TemperatureBar");
export const CompassRose = withLicense(_CompassRose, "CompassRose");
export const Speedometer = withLicense(_Speedometer, "Speedometer");
export const ToggleSwitch = withLicense(_ToggleSwitch, "ToggleSwitch");
export const NumericStepper = withLicense(_NumericStepper, "NumericStepper");
export const SegmentedBar = withLicense(_SegmentedBar, "SegmentedBar");
export const RadarReticle = withLicense(_RadarReticle, "RadarReticle");
export const CrosshairTarget = withLicense(_CrosshairTarget, "CrosshairTarget");
export const MissionStatus = withLicense(_MissionStatus, "MissionStatus");

// Re-export types (no license needed)
export type { OrbitSystemProps, OrbitSatellite } from "./_raw.js";
export type { TargetReticleProps } from "./_raw.js";
export type { PriorityBadgeProps } from "./_raw.js";
export type { RegistrationMarkProps } from "./_raw.js";
export type { ArchiveTagProps } from "./_raw.js";
export type { SignalMeterProps } from "./_raw.js";
export type { PulseTagProps } from "./_raw.js";
export type { StatusLightProps } from "./_raw.js";
export type { HeartbeatLineProps } from "./_raw.js";
export type { LoadBarProps } from "./_raw.js";
export type { BootSequenceProps } from "./_raw.js";
export type { BatteryMeterProps } from "./_raw.js";
export type { UptimeProps } from "./_raw.js";
export type { DotChartProps } from "./_raw.js";
export type { BarSparklineProps } from "./_raw.js";
export type { FrequencyBarsProps } from "./_raw.js";
export type { BinaryStreamProps } from "./_raw.js";
export type { VUMeterProps } from "./_raw.js";
export type { GlitchCyclerProps } from "./_raw.js";
export type { TypewriterProps } from "./_raw.js";
export type { GlitchTextProps } from "./_raw.js";
export type { LogStreamProps } from "./_raw.js";
export type { CounterUpProps } from "./_raw.js";
export type { BootLogProps } from "./_raw.js";
export type { CornerOrnamentProps } from "./_raw.js";
export type { BarcodeProps } from "./_raw.js";
export type { PanelTitleProps } from "./_raw.js";
export type { PixelDiamondProps } from "./_raw.js";
export type { PixelClockProps } from "./_raw.js";
export type { UnixTimestampProps } from "./_raw.js";
export type { DayProgressProps } from "./_raw.js";
export type { DialGaugeProps } from "./_raw.js";
export type { TankLevelProps } from "./_raw.js";
export type { FlowMeterProps } from "./_raw.js";
export type { CopyButtonProps } from "./_raw.js";
export type { RatingDotsProps } from "./_raw.js";
export type { SpinDialProps } from "./_raw.js";
export type { ScanBeamProps } from "./_raw.js";
export type { KanaTagProps } from "./_raw.js";
export type { MicroStripProps } from "./_raw.js";
export type { WeatherStripProps } from "./_raw.js";
export type { WaveformLineProps } from "./_raw.js";
export type { RadarSweepProps } from "./_raw.js";
export type { PacketFlowProps } from "./_raw.js";
export type { HeatGridProps } from "./_raw.js";
export type { ThermalBarProps } from "./_raw.js";
export type { SystemLoadProps } from "./_raw.js";
export type { EventTickerProps } from "./_raw.js";
export type { CountdownTimerProps } from "./_raw.js";
export type { StopwatchDisplayProps } from "./_raw.js";
export type { TimezoneBarProps } from "./_raw.js";
export type { PressureGaugeProps } from "./_raw.js";
export type { VoltageDisplayProps } from "./_raw.js";
export type { TemperatureBarProps } from "./_raw.js";
export type { CompassRoseProps } from "./_raw.js";
export type { SpeedometerProps } from "./_raw.js";
export type { ToggleSwitchProps } from "./_raw.js";
export type { NumericStepperProps } from "./_raw.js";
export type { SegmentedBarProps } from "./_raw.js";
export type { RadarReticleProps } from "./_raw.js";
export type { CrosshairTargetProps } from "./_raw.js";
export type { MissionStatusProps } from "./_raw.js";
export type { ScrollingTextProps } from "./_raw.js";
export type { BinaryCounterProps } from "./_raw.js";
export type { SectorBadgeProps } from "./_raw.js";
export type { RulerTickProps } from "./_raw.js";
export type { CoordLabelProps } from "./_raw.js";
export type { WireFrameProps } from "./_raw.js";
export type { HexGridProps } from "./_raw.js";
export type { SignalQualityProps } from "./_raw.js";
export type { WatchdogTimerProps } from "./_raw.js";

// Export license utilities
export { useLicense } from "./useLicense.js";
export { initLicense, shouldRender, getLicenseStatus, isLicensed, getTrialRemaining } from "@micrographics-js/core";
